version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: health-postgres
    ports:
      - "5433:5432" # Port local:Port conteneur
    environment:
      POSTGRES_DB: healthdb
      POSTGRES_USER: healthuser
      POSTGRES_PASSWORD: healthpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
